{% set version = "1.2.10" %}

package:
  name: rasterio
  version: {{ version }}

source:
  url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
  sha256: f9df8548e8a053d5db6057a4fd28d940d98a06d249f8af9e8fde1d8e9587d0b5

build:
  number: 3
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - libgdal
    - proj
  run:
    - python
    - setuptools >=0.9.8
    - libgdal
    - affine
    - attrs
    - certifi
    - click >=4
    - cligj >=0.5
    - {{ pin_compatible('numpy') }}
    - snuggs >=1.4.1
    - click-plugins
    - proj

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest >=2.8.2
    - pytest-cov >=2.2.0
    - ipython >=2.0
    - boto3 >=1.2.4
    - matplotlib-base
    - packaging
    - hypothesis
    - shapely
  files:
    - test_data/test.tif
  imports:
    - rasterio
  commands:
    - rio --help
    - rio info {{ RECIPE_DIR }}/test_data/test.tif  # [not win]
    - rio info {{ RECIPE_DIR }}\\test_data\\test.tif  # [win]
    # test_target_aligned_pixels is failing for all OSes for proj 8.0.0
    - $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not test_target_aligned_pixels" tests  # [linux and target_platform != "linux-aarch64"]
    - $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not (test_target_aligned_pixels or test_outer_boundless_pixel_fidelity)" tests  # [linux and target_platform == "linux-aarch64"]
    - $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not (test_target_aligned_pixels or test_reproject_error_propagation or test_outer_boundless_pixel_fidelity)" tests  # [osx]
    - python -m pytest -v -m "not wheel" -rxXs -k "not (test_hit_ovr or test_file_in_handler_with_vfs or test_files or test_parse_windows_path or test_copyfiles_same_dataset_another_name or test_context or test_target_aligned_pixels or test_decimated_no_use_overview or test_reproject_error_propagation)" tests  # [win]
    - pip check
about:
  home: https://github.com/mapbox/rasterio
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Rasterio reads and writes geospatial raster datasets

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
    - snowman2
    - xylar
    - akrherz
