{% set version = "1.0.25" %}

package:
  name: rasterio
  version: {{ version }}

source:
  url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
  sha256: 22c2afc282352afddc1a4fedfcbd1deaf5224ee05d3f1caef859491eb76e9497

build:
  number: 1
  skip: True  # [win and py27]
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - libgdal 2.4
  run:
    - python
    - setuptools >=0.9.8
    - libgdal 2.4
    - affine >=1.3.0
    - attrs >=16.0.0
    - click >=4,<8
    - cligj >=0.5
    - {{ pin_compatible('numpy') }}
    - snuggs >=1.4.1
    - click-plugins
    - enum34  # [py<34]
test:
  source_files:
    - tests
  imports:
    - rasterio
  requires:
    - pytest >=2.8.2
    - pytest-cov >=2.2.0
    - boto3 >=1.2.4
    - packaging
    - hypothesis
    - mock  # [py2k]
    - futures  # [py2k]
    - matplotlib  # [not py2k]
  files:
    - test_data/test.tif
  commands:
    - rio --help
    - rio info {{ RECIPE_DIR }}/test_data/test.tif  # [not win]
    - rio info {{ RECIPE_DIR }}\test_data\test.tif  # [win]
    - pytest -s -rxs -v -m "not wheel" tests  # [linux]
    - pytest -s -rxs -v -m "not wheel" -k "not (test_transform_geom_polygon_cutting or test_transform_geom_polygon_offset)" tests  # [osx]
    # Skipping some tests in Windows due to, most of them looks like file lock issues.
    - pytest -s -rxs -v -m "not wheel" -k "not (test_hit_ovr or test_file_in_handler_with_vfs or test_wrap_file or test_hit_ovr)" tests  # [win]

about:
  home: https://github.com/mapbox/rasterio
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Rasterio reads and writes geospatial raster datasets'

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
    - snowman2
