{% set version = "1.2.9" %}

package:
  name: rasterio
  version: {{ version }}

source:
  url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
  sha256: 589729d70a742b8c157be299884810ecd930607eb9a6c4e56715cd5cfa1af376

build:
  number: 1
  entry_points:
    - rio = rasterio.rio.main:main_group
  skip: true  # [win and py<=36]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - libgdal
    # not an explicit dependency but tests clearly depend on proj version
    - proj
  run:
    - python
    - setuptools >=0.9.8
    - libgdal
    - affine
    - attrs
    - click >=4
    - cligj >=0.5
    - {{ pin_compatible('numpy') }}
    - snuggs >=1.4.1
    - click-plugins
    # not an explicit dependency but tests clearly depend on proj version
    # test_target_aligned_pixels fails for proj 8.0.0
    - proj

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest >=2.8.2
    - pytest-cov >=2.2.0
    - ipython >=2.0
    - boto3 >=1.2.4
    - matplotlib-base
    - packaging
    - hypothesis
    - shapely
  files:
    - test_data/test.tif
  imports:
    - rasterio
  commands:
    - rio --help
    - rio info {{ RECIPE_DIR }}/test_data/test.tif  # [not win]
    - rio info {{ RECIPE_DIR }}\\test_data\\test.tif  # [win]
    # test_target_aligned_pixels is failing for all OSes for proj 8.0.0
    - $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not test_target_aligned_pixels" tests  # [not win]
    - python -m pytest -v -m "not wheel" -rxXs -k "not (test_hit_ovr or test_file_in_handler_with_vfs or test_files or test_parse_windows_path or test_copyfiles_same_dataset_another_name or test_context or test_target_aligned_pixels or test_decimated_no_use_overview)" tests  # [win]
    - pip check
about:
  home: https://github.com/mapbox/rasterio
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Rasterio reads and writes geospatial raster datasets

extra:
  recipe-maintainers:
    - ocefpaf
    - ceholden
    - snowman2
    - xylar
    - akrherz
