{% set tests_to_skip = "test_reproject_view" %}
{% set version = "1.3.8" %}

package:
  name: rasterio
  version: {{ version }}

source:
  url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
  sha256: 3aadf26b15ba601d45f3e8e3d67ee99aa673f71631ed806492967fb40716bce3

build:
  skip: true  # [py<38]
  number: 0
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - libgdal
    - proj
  run:
    - python
    - setuptools >=0.9.8
    - libgdal
    - affine
    - attrs
    - certifi
    - click >=4
    - cligj >=0.5
    - {{ pin_compatible('numpy') }}
    - snuggs >=1.4.1
    - click-plugins
    - proj

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest >=2.8.2
    - pytest-cov >=2.2.0
    - ipython >=2.0
    - boto3 >=1.2.4
    - matplotlib-base
    - packaging
    - hypothesis
    - shapely
  files:
    - test_data/test.tif
  imports:
    - rasterio
  commands:
    - rio --help
    - rio info {{ RECIPE_DIR }}/test_data/test.tif  # [not win]
    - rio info {{ RECIPE_DIR }}\\test_data\\test.tif  # [win]
    # skip linux tests for cross-compiled targets
    # xylar 2022-Jul-6: disabling test_search_gdal_data_debian and test_decimated_no_use_overview under win.
    #                   test_decimated_no_use_overview fails because of trying to overwrite an existing file.
    # akrherz 2023-Feb-26: tests that fail on GDAL 3.6.2, but work on 3.6.0, shrug
    {% set tests_to_skip = "test_reproject_view" %}
    {% set tests_to_skip = tests_to_skip + " or test_reproject_nodata" %}
    {% set tests_to_skip = tests_to_skip + " or test_reproject_nodata_nan" %}
    {% set tests_to_skip = tests_to_skip + " or test_reproject_dst_nodata_default" %}
    # weiji14 2023-May-2: disable test_transform_bounds_densify that fails on PROJ9.2.0
    # Remove after rasterio 1.3.7 or above, see https://github.com/rasterio/rasterio/issues/2789
    {% set tests_to_skip = tests_to_skip + " or test_transform_bounds_densify" %}
    - $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not ({{ tests_to_skip }})" tests  # [linux and build_platform == target_platform]
    - $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not ({{ tests_to_skip }})" tests  # [osx]
    - python -m pytest -v -m "not wheel" -rxXs -k "not (test_search_gdal_data_debian or test_decimated_no_use_overview or test_copyfiles_same_dataset_another_name or {{ tests_to_skip }})" tests  # [win]
    - pip check
about:
  home: https://github.com/rasterio/rasterio
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Rasterio reads and writes geospatial raster datasets

extra:
  recipe-maintainers:
    - weiji14
    - ocefpaf
    - ceholden
    - snowman2
    - xylar
    - akrherz
