{% set tests_to_skip = "test_merge_out_of_range_nodata" %}
{% set version = "1.4.3" %}

package:
  name: rasterio
  version: {{ version }}

source:
  url: https://github.com/mapbox/rasterio/archive/{{ version }}.tar.gz
  sha256: dfa248fdc46f0e08ab957712b13a86d7cd49bce72f34b7fdca94af3b2d850181

build:
  number: 1
  entry_points:
    - rio = rasterio.rio.main:main_group

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=1.24                           # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy >=1.24
    - libgdal-core
    - proj
    - setuptools
  run:
    - python
    - setuptools >=0.9.8
    - libgdal-core
    - affine
    - attrs
    - boto3 >=1.3.1
    - certifi
    - click >=4
    - cligj >=0.5
    - importlib-metadata  # [py<310]
    - snuggs >=1.4.1
    - click-plugins
    - proj

test:
  source_files:
    - tests
  requires:
    - pip
    # awaiting upstream pytest=8 support
    - pytest >=2.8.2,<8
    - pytest-cov >=2.2.0
    - ipython >=2.0
    - aiohttp
    - fsspec
    - hypothesis
    - libgdal-netcdf
    - matplotlib-base
    - packaging
    - requests
    - shapely
  files:
    - test_data/test.tif
  imports:
    - rasterio
  commands:
    - rio --help
    - rio info {{ RECIPE_DIR }}/test_data/test.tif  # [not win]
    - rio info {{ RECIPE_DIR }}\\test_data\\test.tif  # [win]
    # skip linux tests for cross-compiled targets
    # xylar 2022-Jul-6: disabling test_search_gdal_data_debian and test_decimated_no_use_overview under win.
    #                   test_decimated_no_use_overview fails because of trying to overwrite an existing file.
    # unknown numpy 2 segfault
    {% set tests_to_skip = "test_merge_out_of_range_nodata" %}
    # {% set tests_to_skip = tests_to_skip + " or test_<placeholder>" %}
    - $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not ({{ tests_to_skip }})" tests  # [linux and build_platform == target_platform]
    - $PYTHON -m pytest -v -m "not wheel" -rxXs -k "not ({{ tests_to_skip }})" tests  # [osx]
    - python -m pytest -v -m "not wheel" -rxXs -k "not (test_search_gdal_data_debian or test_decimated_no_use_overview or test_copyfiles_same_dataset_another_name or {{ tests_to_skip }})" tests  # [win]
    - pip check
about:
  home: https://github.com/rasterio/rasterio
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Rasterio reads and writes geospatial raster datasets

extra:
  recipe-maintainers:
    - weiji14
    - ocefpaf
    - ceholden
    - snowman2
    - akrherz
