travis:
  secure:
    BINSTAR_TOKEN: qF9XjT4xWNE8XUgtkuxT0YX3B4nUepFl558KOGnsxsWFrWKZKKyrdXdodLWUHUXBwOKuKO+s6tgLAVCoUmAGXhfiU5zIBN4bJnvC1earG6fgyJCDuKPsTQ/5lHGz3+/Ch/KnP1FAzo6BBHz8ZGbE0A9cIVWSbc6jTyW8iKy6l+CyTl9oEuXWEGuYYKRt/fCJzwQGDpK6C/Pll4vgB+nIXfe4M+5b0Hp0GUbgZ/zhT/vfAQ6n8bAMWws30dl/lhu7jbjvr2s9ADq8mU2EtKuWDuR/Wo0mkHRI1PzOYVoQVyE3T6ZwfziCywUrX0XSOLYWyremEgmpQ28ps5eo9NiKu+MlD+Wqljox3i0fBKmqhjPJRwn90wIAb9BVviksLnPXArgsBUM3CbY4Z8olTyyvpoz4LU2HW8fGBtpBZVv02ctw2Xphw9HOk+z//0UIk/UdTCZGQ9JQVKnjUHC4qvkZRdImo4e2KEJQ8Ec/0y22JkVzdJfnEaW3Tx/YloBZQLD83JTkY6K4oTTA7fzyRtR1gwOyUVLjeqy9mYwNFjJChIve7OGduAjXagG6cb7EGThi2tIxF69bCzH/qjM90Afh3t5cdzgRvmGOgPpfauwF20LFU+rr1KBqaHhZQM07y0fCN5QpBDgBaxyeLR8iqO2oo10Pr/SzLX7Ahd00pRWnESc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
max_py_ver: '37'
